root: true
parser: "@typescript-eslint/parser"
parserOptions:
  jsx: true
  useJSXTextNode: true
  ecmaVersion: 2018
  sourceType: module
  project:
    - "./tsconfig.json"
    - "./packages/*/tsconfig.json"
ignorePatterns:
  - ".eslintrc.js"
  - node_modules
  - "**/types/*.d.ts"
  - include
  - out
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - "./tsconfig.json"
        - "./packages/*/tsconfig.json"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
plugins:
  - "@typescript-eslint"
  - unused-imports
  - import
  - unicorn
  - roblox-ts
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/typescript
  - plugin:unicorn/recommended
  - plugin:roblox-ts/recommended
  - plugin:prettier/recommended
reportUnusedDisableDirectives: true
rules:
  camelcase: 0
  no-undef: 0
  no-shadow: 0
  no-console: 1
  no-unused-vars: 0
  no-empty-pattern: 0
  no-await-in-loop: 0
  no-param-reassign: 0
  consistent-return: 0
  no-use-before-define: 0
  no-restricted-syntax: 0
  no-negated-condition: 2
  no-implicit-coercion:
    - 1
    - boolean: false
      number: true
      string: true
  no-restricted-globals: 0
  no-shadow-restricted-names: 2
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-unused-vars": 0
  sonarjs/no-identical-functions: 0
  sonarjs/cognitive-complexity: 0
  sonarjs/no-duplicate-string: 0
  sonarjs/no-ignored-return: 0
  unicorn/prevent-abbreviations: 0
  unicorn/no-useless-undefined: 0
  unicorn/prefer-node-protocol: 0
  unicorn/catch-error-name: 0
  unicorn/no-array-reduce: 0
  unicorn/filename-case: 0
  unicorn/prefer-module: 0
  unicorn/no-null: 0
  import/default: 0
  import/extensions: 0
  import/no-deprecated: 1
  import/no-duplicates: 2
  import/no-unresolved: 1
  import/no-extraneous-dependencies: 0
  import/order:
    - 2
    - alphabetize:
        order: asc
      groups:
        - - builtin
          - external
          - internal
        - - unknown
          - parent
          - sibling
        - index
      newlines-between: always
  unused-imports/no-unused-imports: 1
  unused-imports/no-unused-vars: 0
  prettier/prettier: 1
